services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sns,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
